### ISSUE TITLE
how can i  get the final result

### ISSUE THREAD

**Issue by baifan2618** [JayKumarr/OSGM#1]
According to the readme, only the cluster number of each document can be obtained.

**from evaluate import evaluate_results**

Can you provide this module, Thank you

**Comment by JayKumarr** [comment]
I have uploaded evaluate.py, kindly refresh the repository.

def evaluate_results(dataset, prediction_dir, stats_dir):
    # if (not os.path.exists(stats_dir)):
    #     os.makedirs(stats_dir)
    classDocMap, docsClassMap = ut.loadOrigialDocClassLabels(dataset)
    highest_nmi, highest_nmi_file = evaluate(classDocMap,docsClassMap,prediction_dir, stats_dir)
    print("----------- HIGHEST NMI --------")
    print(highest_nmi_file," ", highest_nmi)
